<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE6qCPv1\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE6qCPv1/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerE6qCPv1.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerE6qCPv1\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerE6qCPv1\appAppKernelProdContainer([
    'container.build_hash' => 'E6qCPv1',
    'container.build_id' => '70a440b5',
    'container.build_time' => 1699868116,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE6qCPv1');
